services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "src/app/consumer.py"]

volumes:
  db_data:
